---
- hosts: nodes
  vars_files:
    - vars/userlist.yml
  tasks:
    - name: add users
      user:
        name: '{{ item.key }}'
        comment: '{{ item.key }}@example.com'
        password: "{{ item.value.password | password_hash('sha512') }}"
        state: present
        update_password: on_create
      loop: "{{ lookup('dict', users) }}"
      no_log: true

