- hosts: nodes
  vars_files:
    - vars/credentials.yml
  tasks:
    - name: add users
      user:
        name: '{{ item.name }}'
        comment: '{{ item.name }}@example.com'
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
        update_password: on_create
      with_items: '{{ user_details }}'
      no_log: true
