---
- hosts: nodes
  vars_files:
    - vars/userlist.yml
  tasks:
    - name: remove users
      user:
        name: '{{ item }}'
        remove: true 
        state: absent
      with_items: '{{ users }}'
