---
- hosts: nodes
  vars_files:
    - vars/userlist.yml
  tasks:
    - name: remove users
      user:
        name: '{{ item.key }}'
        remove: true 
        state: absent
      loop: "{{ lookup('dict', users) }}"
